### ISSUE TITLE
Navigating settings with keyboard crashes the screen

### ISSUE THREAD

**Issue by ZtereoHYPE** [ZtereoHYPE/nicer-skies#17]
This is due to poor handling of the narrator

**Comment by ZtereoHYPE** [comment]
```
net.minecraft.ReportedException: Narrating screen
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1215) ~[minecraft-merged-named.jar:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1112) ~[minecraft-merged-named.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:712) ~[minecraft-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:229) ~[minecraft-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.gui.components.Button$CreateNarration.createNarrationMessage(java.util.function.Supplier)" because "this.createNarration" is null
	at net.minecraft.client.gui.components.Button.createNarrationMessage(Button.java:37) ~[minecraft-merged-named.jar:?]
	at net.minecraft.client.gui.components.AbstractWidget.defaultButtonNarrationText(AbstractWidget.java:310) ~[minecraft-merged-named.jar:?]
	at net.minecraft.client.gui.components.Button.updateWidgetNarration(Button.java:42) ~[minecraft-merged-named.jar:?]
	at net.minecraft.client.gui.components.AbstractWidget.updateNarration(AbstractWidget.java:301) ~[minecraft-merged-named.jar:?]
	at net.minecraft.client.gui.screens.Screen.updateNarratedWidget(Screen.java:521) ~[minecraft-merged-named.jar:?]
	at net.minecraft.client.gui.screens.Screen.updateNarrationState(Screen.java:502) ~[minecraft-merged-named.jar:?]
	at net.minecraft.client.gui.narration.ScreenNarrationCollector.update(ScreenNarrationCollector.java:19) ~[minecraft-merged-named.jar:?]
	at net.minecraft.client.gui.screens.Screen.runNarration(Screen.java:485) ~[minecraft-merged-named.jar:?]
	at net.minecraft.client.gui.screens.Screen.handleDelayedNarration(Screen.java:472) ~[minecraft-merged-named.jar:?]
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1209) ~[minecraft-merged-named.jar:?]
```

**Comment by ZtereoHYPE** [comment]
fixed, narrator :P
